#!/system/bin/sh
# Move dalvik-cache to cache By: JoseGalRe

if [ ! -d /cache/dalvik-cache ]; then
    busybox rm -rf /cache/dalvik-cache /data/dalvik-cache;
    mkdir /cache/dalvik-cache /data/dalvik-cache;
fi;

busybox chown 1000:1000 /cache/dalvik-cache;
busybox chmod 0771 /cache/dalvik-cache;
busybox mount -o bind /cache/dalvik-cache /data/dalvik-cache;
busybox chown 1000:1000 /data/dalvik-cache;
busybox chmod 0771 /data/dalvik-cache;
