LOCAL_PATH := $(call my-dir)

ifeq ($(BOARD_HAVE_SAMSUNG_WIFI),true)

ifdef WIFI_DRIVER_NVRAM_PATH
LOCAL_CFLAGS += -DWIFI_DRIVER_NVRAM_PATH=\"$(WIFI_DRIVER_NVRAM_PATH)\"
endif

ifdef WIFI_DRIVER_NVRAM_PATH_PARAM
LOCAL_CFLAGS += -DWIFI_DRIVER_NVRAM_PATH_PARAM=\"$(WIFI_DRIVER_NVRAM_PATH_PARAM)\"
endif

include $(CLEAR_VARS)
LOCAL_MODULE           := macloader
LOCAL_MODULE_TAGS      := optional
LOCAL_SHARED_LIBRARIES := liblog libutils
LOCAL_SRC_FILES        := macloader.c
include $(BUILD_EXECUTABLE)

endif
